<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract-module' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    '<strong>Meeting</strong> overview' => '',
    'Drag entry' => '',
    'Duplicate' => '',
    'Edit' => '',
    'Edit a protocol' => '',
    'Filter meetings by title' => '',
    'Location' => '',
    'Note: This agenda entry still uses a legacy time format, please save all legacy items in order to use new features.' => '',
    'There are currently no upcoming meetings!.' => '',
    'at' => '',
    '<strong>Next</strong> meetings' => '<strong>Przyszłe</strong> spotkania',
    'Add a protocol' => 'Dodaj protokół',
    'Add a task' => 'Dodaj zadanie',
    'Create your first agenda entry by clicking the following button.' => 'Utwórz swój pierwszy plan spotkania klikając ten przycisk.',
    'External participants' => 'Zewnętrzni uczestnicy',
    'Moderators' => 'Moderatorzy',
    'New agenda entry' => 'Nowy plan spotkania',
    'New meeting' => 'Nowe spotkanie',
    'Participants' => 'Uczestnicy',
    'Print agenda' => 'Drukuj plan',
    'Protocol' => 'Protokół',
    'Share meeting' => 'Podziel się spotkaniem',
    'Start now, by creating a new meeting!' => 'Zacznij już teraz, tworząc nowe spotkanie!',
    'Tasks' => 'Zadania',
    'Today' => 'Dzisiaj',
    'Tomorrow' => 'Jutro',
];
